import json
import logging
from sqlalchemy.orm import Session
from app.models.interview import InterviewSession, Report, Evaluation, InterviewQuestion, InterviewAnswer
from app.models.candidate_profile import CandidateProfile
from app.utils.ai_client import generate_text

logger = logging.getLogger("report_generator")


class ReportGenerator:
    def __init__(self, db: Session) -> None:
        self.db = db

    async def generate_report(self, session_id: int) -> Report:
        """
        Synthesize evaluations and metrics to produce a detailed Report.
        Uses Gemini API if available, falls back to structural analytics.
        """
        # Fetch all questions and evaluations
        session = self.db.get(InterviewSession, session_id)
        if not session:
            raise ValueError(f"Interview session {session_id} not found.")

        evaluations = (
            self.db.query(Evaluation)
            .join(InterviewAnswer)
            .join(InterviewQuestion)
            .filter(InterviewQuestion.session_id == session_id)
            .all()
        )

        profile = self.db.query(CandidateProfile).filter(CandidateProfile.user_id == session.candidate_id).first()

        # Aggregate scores
        r1_evals = [e for e in evaluations if e.answer.question.round_number == 1]
        r2_evals = [e for e in evaluations if e.answer.question.round_number == 2]

        r1_score = sum(e.score for e in r1_evals) / len(r1_evals) if r1_evals else 0.0
        r2_score = sum(e.score for e in r2_evals) / len(r2_evals) if r2_evals else 0.0

        overall_score = session.cumulative_score

        # Determine Recommendation
        if overall_score >= 7.5:
            recommendation = "Ready for Interview"
        elif overall_score >= 5.0:
            recommendation = "Needs Improvement"
        else:
            recommendation = "Not Recommended"

        # Combine strengths & weaknesses
        all_strengths = []
        all_weaknesses = []
        for e in evaluations:
            if e.strengths:
                all_strengths.append(e.strengths)
            if e.weaknesses:
                all_weaknesses.append(e.weaknesses)

        # Try query LLM for a summarized profile & professional path
        prompt = self._build_prompt(session, evaluations, overall_score, recommendation)
        system_instruction = (
            "You are a Principal Technical Recruiter and Engineering Manager. Summarize the interview results and produce a professional evaluation report. "
            "You must output your analysis strictly as a valid JSON object. Do not include markdown formatted JSON wrapper blocks. "
            "Output must match this schema:\n"
            "{\n"
            "  \"strengths\": [\"string\"],\n"
            "  \"weaknesses\": [\"string\"],\n"
            "  \"summary_notes\": \"string\",\n"
            "  \"learning_path\": [\n"
            "     {\"title\": \"string\", \"description\": \"string\", \"resources\": [\"string\"]}\n"
            "  ]\n"
            "}"
        )

        response = await generate_text(prompt, system_instruction)
        if response:
            try:
                # Clean up any potential markdown wrap
                clean_response = response.strip()
                if clean_response.startswith("```"):
                    clean_response = clean_response.split("```")[1]
                    if clean_response.startswith("json"):
                        clean_response = clean_response[4:]
                clean_response = clean_response.strip()

                result = json.loads(clean_response)
                
                # Check keys
                if "strengths" in result and "weaknesses" in result and "learning_path" in result:
                    report = Report(
                        session_id=session_id,
                        overall_score=round(overall_score, 1),
                        round1_score=round(r1_score, 1),
                        round2_score=round(r2_score, 1),
                        strengths=json.dumps(result["strengths"]),
                        weaknesses=json.dumps(result["weaknesses"]),
                        learning_path=json.dumps(result["learning_path"]),
                        hiring_recommendation=recommendation,
                        summary_notes=result.get("summary_notes", "Summary generated by AI Interviewer."),
                    )
                    self.db.add(report)
                    session.status = "COMPLETED"
                    self.db.commit()
                    self.db.refresh(report)
                    return report
            except Exception as e:
                logger.error(f"Failed to parse LLM report generator response: {e}. Raw response: {response}")

        # Fallback structural report builder
        report = self._generate_fallback(session_id, session, overall_score, r1_score, r2_score, recommendation, all_strengths, all_weaknesses)
        session.status = "COMPLETED"
        self.db.commit()
        return report

    def _build_prompt(
        self,
        session: InterviewSession,
        evaluations: list[Evaluation],
        overall_score: float,
        recommendation: str
    ) -> str:
        eval_history = ""
        for i, e in enumerate(evaluations):
            eval_history += (
                f"Q{i+1}: {e.answer.question.question_text}\n"
                f"Answer: {e.answer.answer_text}\n"
                f"Score: {e.score}\n"
                f"Strengths: {e.strengths}\n"
                f"Weaknesses: {e.weaknesses}\n\n"
            )

        return (
            f"Candidate Role: {session.job_role}\n"
            f"Interview Difficulty: {session.difficulty}\n"
            f"Overall Cumulative Score: {overall_score}/10\n"
            f"Hiring Decision: {recommendation}\n\n"
            f"Answer Evaluation Logs:\n{eval_history}\n"
            f"Generate a final assessment. Condense the strengths and weaknesses into a list of 3 items each. "
            f"Write a summary paragraph explaining why this decision was reached. "
            f"Provide a structured learning path with 2 modules mapping specific areas of improvement (including title, description, and link resources like blogs or tutorials)."
        )

    def _generate_fallback(
        self,
        session_id: int,
        session: InterviewSession,
        overall_score: float,
        r1_score: float,
        r2_score: float,
        recommendation: str,
        all_strengths: list[str],
        all_weaknesses: list[str]
    ) -> Report:
        # Condense lists to unique items
        strengths = list(set(all_strengths))[:3]
        weaknesses = list(set(all_weaknesses))[:3]

        if not strengths:
            strengths = ["Demonstrated fundamental coding structure.", "Clear and polite communication style."]
        if not weaknesses:
            weaknesses = ["Could expand explanations on architecture design.", "Should dive deeper into scaling tradeoffs."]

        summary_notes = (
            f"The candidate was assessed for the role of {session.job_role} at {session.difficulty} difficulty. "
            f"They completed the assessment with an overall score of {round(overall_score, 1)} out of 10.0. "
            f"They performed stably in Round 1 (Score: {round(r1_score, 1)}) and addressed design and scenario questions in "
            f"Round 2 (Score: {round(r2_score, 1)}). The final recommendation is {recommendation}."
        )

        # Generate a personalized learning path
        learning_path = [
            {
                "title": f"Deep Dive into {session.job_role} Core Concepts",
                "description": f"Master the architectural principles, limits, and advanced frameworks for {session.job_role}.",
                "resources": ["https://roadmap.sh", "https://medium.com/engineering-concepts"]
            },
            {
                "title": "Systems Design & Distributed Scales",
                "description": "Improve your grasp of data consistency, sharding, caching strategies, and CAP theorem trade-offs.",
                "resources": ["https://github.com/donnemartin/system-design-primer", "https://bytebytego.com"]
            }
        ]

        report = Report(
            session_id=session_id,
            overall_score=round(overall_score, 1),
            round1_score=round(r1_score, 1),
            round2_score=round(r2_score, 1),
            strengths=json.dumps(strengths),
            weaknesses=json.dumps(weaknesses),
            learning_path=json.dumps(learning_path),
            hiring_recommendation=recommendation,
            summary_notes=summary_notes,
        )
        self.db.add(report)
        self.db.commit()
        self.db.refresh(report)
        return report
