# Generated by Django 5.0.6 on 2026-07-03 09:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('interview_type', models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR'), ('behavioral', 'Behavioral'), ('aptitude', 'Aptitude')], max_length=20)),
                ('domain', models.CharField(max_length=120)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('question_count', models.PositiveSmallIntegerField(default=5)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_type', models.CharField(max_length=20)),
                ('domain', models.CharField(blank=True, max_length=120)),
                ('difficulty', models.CharField(default='medium', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='scheduled', max_length=20)),
                ('mode', models.CharField(choices=[('scripted', 'Scripted (legacy, turn-by-turn)'), ('realtime', 'Realtime voice conversation')], db_index=True, default='realtime', max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('video_recording', models.FileField(blank=True, null=True, upload_to='sessions/video/')),
                ('audio_recording', models.FileField(blank=True, null=True, upload_to='sessions/audio/')),
                ('realtime_provider', models.CharField(blank=True, default='', max_length=20)),
                ('call_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('call_join_url', models.URLField(blank=True, default='', max_length=1000)),
                ('interrupt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='resume.resume')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='interview.interviewtemplate')),
            ],
            options={
                'db_table': 'interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('difficulty', models.CharField(default='medium', max_length=10)),
                ('expected_topics', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('asked', 'Asked')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seed_topics', to='interview.interviewsession')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.interviewtemplate')),
            ],
            options={
                'db_table': 'interview_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speaker', models.CharField(choices=[('ai', 'AI Interviewer'), ('candidate', 'Candidate')], max_length=10)),
                ('turn_type', models.CharField(choices=[('question', 'Question'), ('follow_up', 'Follow-up'), ('answer', 'Answer'), ('clarification', 'Clarification'), ('small_talk', 'Small talk'), ('system', 'System')], default='answer', max_length=20)),
                ('text', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('started_at_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ended_at_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('was_interrupted', models.BooleanField(default=False, help_text='True if the candidate started speaking before this turn finished.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='interview.interviewsession')),
                ('seed_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turns', to='interview.question')),
            ],
            options={
                'db_table': 'interview_conversation_turns',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('answer_text', models.TextField(blank=True)),
                ('answer_audio', models.FileField(blank=True, null=True, upload_to='sessions/answers/audio/')),
                ('answer_video', models.FileField(blank=True, null=True, upload_to='sessions/answers/video/')),
                ('response_time_seconds', models.FloatField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interview.interviewsession')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interview.question')),
            ],
            options={
                'db_table': 'session_answers',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RealtimeEventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='ultravox', max_length=20)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_events', to='interview.interviewsession')),
            ],
            options={
                'db_table': 'interview_realtime_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['candidate', 'status'], name='interview_s_candida_bfa308_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationturn',
            index=models.Index(fields=['session', 'order'], name='interview_c_session_5fa0c0_idx'),
        ),
    ]
