# Generated by Django 5.0.6 on 2026-07-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_transcript_answerevaluation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='threadevaluation',
            new_name='interview_t_intervi_961498_idx',
            old_name='threadevaluation_interview_idx',
        ),
        migrations.RenameIndex(
            model_name='transcript',
            new_name='interview_t_intervi_770c39_idx',
            old_name='transcript_interview_seq_idx',
        ),
        migrations.RenameIndex(
            model_name='transcript',
            new_name='interview_t_intervi_e7ab40_idx',
            old_name='transcript_interview_speaker_idx',
        ),
        migrations.AlterField(
            model_name='interviewbrief',
            name='contradiction_detail',
            field=models.TextField(blank=True, help_text='Description of what was contradicted and where.'),
        ),
        migrations.AlterField(
            model_name='interviewbrief',
            name='overall_signal',
            field=models.CharField(blank=True, choices=[('strong', 'Strong across topics'), ('mixed', 'Mixed — strong on some, weak on others'), ('surface', 'Surface-level throughout'), ('inconsistent', 'Inconsistent — possible bluffing on some topics')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='interviewbrief',
            name='performs_under_pressure',
            field=models.BooleanField(help_text='True if answers consistently deepened under follow-up probing.', null=True),
        ),
        migrations.AlterField(
            model_name='interviewbrief',
            name='self_contradictions_detected',
            field=models.BooleanField(default=False, help_text='True if the candidate contradicted themselves across topics.'),
        ),
        migrations.AlterField(
            model_name='interviewbrief',
            name='specificity_consistent',
            field=models.BooleanField(help_text='True if candidate gave concrete details consistently across topics.', null=True),
        ),
        migrations.AlterField(
            model_name='interviewbrief',
            name='suggested_followup_questions',
            field=models.JSONField(default=list, help_text='Specific questions for the next human interview round.'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='seed_topics_ready',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='threadevaluation',
            name='conceptual_accuracy',
            field=models.FloatField(blank=True, help_text='Correct use of concepts in context, not just buzzwords. (0–10)', null=True),
        ),
        migrations.AlterField(
            model_name='threadevaluation',
            name='depth_under_pressure',
            field=models.FloatField(blank=True, help_text='Did the candidate go deeper when probed? (0–10)', null=True),
        ),
        migrations.AlterField(
            model_name='threadevaluation',
            name='recovery',
            field=models.FloatField(blank=True, help_text='Handled being wrong or vague gracefully. (0–10)', null=True),
        ),
        migrations.AlterField(
            model_name='threadevaluation',
            name='red_flags',
            field=models.JSONField(default=list, help_text='Quotes or patterns suggesting surface-level knowledge.'),
        ),
        migrations.AlterField(
            model_name='threadevaluation',
            name='specificity',
            field=models.FloatField(blank=True, help_text='Concrete details vs generic statements. (0–10)', null=True),
        ),
        migrations.AlterField(
            model_name='threadevaluation',
            name='strong_signals',
            field=models.JSONField(default=list, help_text='Quotes or patterns suggesting genuine experience.'),
        ),
        migrations.AlterField(
            model_name='threadevaluation',
            name='suggested_followups',
            field=models.JSONField(default=list, help_text='Specific follow-up questions for the next interview round.'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='confidence',
            field=models.FloatField(blank=True, help_text='ASR confidence score from Ultravox (0.0–1.0).', null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Response latency in ms (time between previous turn ending and this one starting).', null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='timestamp',
            field=models.DateTimeField(blank=True, help_text='UTC wall-clock time when this turn was finalised by Ultravox.', null=True),
        ),
    ]
