# Generated by Django 5.0.6 on 2026-07-23 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_rename_threadevaluation_interview_idx_interview_t_intervi_961498_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='current_seed_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interview.question'),
        ),
    ]
