# Generated by Django 5.0.6 on 2026-09-08 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_interview_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewinvitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewinvitation',
            name='token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='client_session_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('opened', 'Opened'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('abandoned', 'Abandoned')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('preparation_failed', 'Preparation Failed'), ('connection_lost', 'Connection Lost'), ('abandoned', 'Abandoned'), ('failed', 'Failed')], db_index=True, default='scheduled', max_length=20),
        ),
        migrations.AddIndex(
            model_name='interviewinvitation',
            index=models.Index(fields=['candidate_email', 'status'], name='interview_i_candida_9271a6_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewinvitation',
            index=models.Index(fields=['token'], name='interview_i_token_327084_idx'),
        ),
    ]
