# Generated by Django 5.0.6 on 2026-07-03 09:41

import apps.resume.models.resume
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.resume.models.resume._upload_path, validators=[apps.resume.models.resume._validate_resume_file])),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('experience_years', models.FloatField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('failure_reason', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resumes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('category', models.CharField(choices=[('skill', 'Skill'), ('technology', 'Technology'), ('tool', 'Tool')], default='skill', max_length=30)),
                ('confidence', models.FloatField(default=1.0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_skills', to='resume.resume')),
            ],
            options={
                'db_table': 'extracted_skills',
            },
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['candidate', 'status'], name='resumes_candida_56fec6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='extractedskill',
            unique_together={('resume', 'name')},
        ),
    ]
