# Generated by Django 5.0.6 on 2026-07-03 09:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grammar_score', models.FloatField()),
                ('clarity_score', models.FloatField()),
                ('completeness_score', models.FloatField()),
                ('filler_penalty', models.FloatField(default=0)),
                ('pace_score', models.FloatField()),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communication_scores',
            },
        ),
        migrations.CreateModel(
            name='ConfidenceScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eye_contact_score', models.FloatField()),
                ('attention_score', models.FloatField()),
                ('engagement_score', models.FloatField()),
                ('emotion_confidence', models.FloatField()),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'confidence_scores',
            },
        ),
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('communication', models.FloatField()),
                ('confidence', models.FloatField()),
                ('technical_relevance', models.FloatField()),
                ('professionalism', models.FloatField()),
                ('overall', models.FloatField(db_index=True)),
                ('rating', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('needs_improvement', 'Needs Improvement'), ('poor', 'Poor')], max_length=20)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'final_scores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalismScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_management_score', models.FloatField()),
                ('organization_score', models.FloatField()),
                ('filler_penalty', models.FloatField(default=0)),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'professionalism_scores',
            },
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('practice_recommendations', models.JSONField(default=list)),
                ('learning_resources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'session_feedback',
            },
        ),
        migrations.CreateModel(
            name='SpeechAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('transcript', models.TextField(blank=True)),
                ('transcription_confidence', models.FloatField(blank=True, null=True)),
                ('grammar_score', models.FloatField(blank=True, null=True)),
                ('filler_word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('filler_words', models.JSONField(blank=True, default=list)),
                ('speaking_pace_wpm', models.FloatField(blank=True, null=True)),
                ('clarity_score', models.FloatField(blank=True, null=True)),
                ('completeness_score', models.FloatField(blank=True, null=True)),
                ('dominant_emotion', models.CharField(blank=True, max_length=30)),
                ('emotion_breakdown', models.JSONField(blank=True, default=dict)),
                ('eye_contact_percentage', models.FloatField(blank=True, null=True)),
                ('attention_score', models.FloatField(blank=True, null=True)),
                ('engagement_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'speech_analyses',
            },
        ),
        migrations.CreateModel(
            name='TechnicalScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword_coverage', models.FloatField()),
                ('completeness', models.FloatField()),
                ('answered_ratio', models.FloatField()),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'technical_scores',
            },
        ),
    ]
