# Generated by Django 5.0.6 on 2026-07-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationscore',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_score', to='interview.interviewsession'),
        ),
        migrations.AddField(
            model_name='confidencescore',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_score', to='interview.interviewsession'),
        ),
        migrations.AddField(
            model_name='finalscore',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_score', to='interview.interviewsession'),
        ),
        migrations.AddField(
            model_name='professionalismscore',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professionalism_score', to='interview.interviewsession'),
        ),
        migrations.AddField(
            model_name='sessionfeedback',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='interview.interviewsession'),
        ),
        migrations.AddField(
            model_name='speechanalysis',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speech_analysis', to='interview.interviewsession'),
        ),
        migrations.AddField(
            model_name='technicalscore',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_score', to='interview.interviewsession'),
        ),
    ]
