# Generated by Django 5.0.6 on 2026-08-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_faceassessmentsnapshot_multiple_faces'),
        ('interview', '0006_interview_invitation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='faceassessmentsnapshot',
            name='unique_face_snapshot_per_session_seq',
        ),
        migrations.AlterUniqueTogether(
            name='faceassessmentsnapshot',
            unique_together={('session', 'sequence')},
        ),
    ]
